"""conversation escalation cols (priority severity card)

Revision ID: 0080e6c2bf8f
Revises: 8df9472b4aaa
Create Date: 2026-07-17 22:56:53.320326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0080e6c2bf8f'
down_revision: Union[str, None] = '8df9472b4aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('priority', sa.String(length=16), nullable=True))
    op.add_column('conversation', sa.Column('severity', sa.String(length=16), nullable=True))
    op.add_column('conversation', sa.Column('escalation_card', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'escalation_card')
    op.drop_column('conversation', 'severity')
    op.drop_column('conversation', 'priority')
    # ### end Alembic commands ###
